### PR TITLE
fix MIT license

### PR DESCRIPTION
**Pull request by apasel422**

### CODE REVIEW

**Comment by FlashCat** [comment]
r? @Gankro

(I've picked a reviewer for you, use r? to override)

**Comment by Gankra** [comment]
r+

**Comment by Gankra** [comment]
oh whoops.

@FlashCat r+

**Comment by FlashCat** [comment]
:pushpin: Commit 6c3446a has been approved by `Gankro`

**Comment by FlashCat** [comment]
:hourglass: Testing commit 6c3446a with merge d7cbdf4...

**Comment by FlashCat** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/contain-rs/enum-set/builds/55027990)

**Comment by FlashCat** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/contain-rs/enum-set/builds/55027990)

**Pull request merged**
