### PR TITLE
Add from_slice() method

### PR DESCRIPTION
**Pull request by upsuper**

### CODE REVIEW

**Comment by FlashCat** [comment]
Thanks for the pull request, and welcome! The contain-rs team is excited to review your changes, and you should hear from @bluss (or someone else) soon.

If any changes to this PR are deemed necessary, please add them as extra commits. This ensures that the reviewer can see what has changed since they last reviewed the code. The way Github handles out-of-date commits, this should also make it reasonably obvious what issues have or haven't been addressed. Large or tricky changes may require several passes of review and changes.

**Comment by bluss** [comment]
Hi!

`FromIterator` already covers this use case, so I'm not sure we actually want this.

What do you think @Gankro?

**Comment by upsuper** [comment]
Oh, I wasn't aware of FromIterator. Then I guess we do not need this.

**Comment by bluss** [comment]
Ok. Most use of FromIterator go through the `.collect()` method on iterators fyi.

**Pull request closed without merging**
