### PR TITLE
Make Iter derive Clone and Copy

### PR DESCRIPTION
**Pull request by upsuper**

### CODE REVIEW

**Comment by FlashCat** [comment]
Thanks for the pull request, and welcome! The contain-rs team is excited to review your changes, and you should hear from @Gankro (or someone else) soon.

If any changes to this PR are deemed necessary, please add them as extra commits. This ensures that the reviewer can see what has changed since they last reviewed the code. The way Github handles out-of-date commits, this should also make it reasonably obvious what issues have or haven't been addressed. Large or tricky changes may require several passes of review and changes.

**Comment by Gankra** [comment]
Thanks!

**Comment by apasel422** [comment]
For what it's worth, I'm unaware of any iterator in `std` or `contain-rs` that implements `Copy`.

**Comment by Gankra** [comment]
Oh actually yeah. We decided against Copy a long time ago because it can do weird things where you think it's iterated but it's not.

**Comment by apasel422** [comment]
I have a cleanup PR incoming.

**Pull request merged**
